// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// day15p1
int day15p1(long sa, long sb, long n);
RcppExport SEXP _AoC2017_day15p1(SEXP saSEXP, SEXP sbSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type sa(saSEXP);
    Rcpp::traits::input_parameter< long >::type sb(sbSEXP);
    Rcpp::traits::input_parameter< long >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(day15p1(sa, sb, n));
    return rcpp_result_gen;
END_RCPP
}
// day15p2
int day15p2(long sa, long sb, long n);
RcppExport SEXP _AoC2017_day15p2(SEXP saSEXP, SEXP sbSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type sa(saSEXP);
    Rcpp::traits::input_parameter< long >::type sb(sbSEXP);
    Rcpp::traits::input_parameter< long >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(day15p2(sa, sb, n));
    return rcpp_result_gen;
END_RCPP
}
// day17p2
int day17p2(long offset, long n);
RcppExport SEXP _AoC2017_day17p2(SEXP offsetSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< long >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(day17p2(offset, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AoC2017_day15p1", (DL_FUNC) &_AoC2017_day15p1, 3},
    {"_AoC2017_day15p2", (DL_FUNC) &_AoC2017_day15p2, 3},
    {"_AoC2017_day17p2", (DL_FUNC) &_AoC2017_day17p2, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_AoC2017(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
