# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

day15p1 <- function(sa, sb, n) {
    .Call('_AoC2017_day15p1', PACKAGE = 'AoC2017', sa, sb, n)
}

day15p2 <- function(sa, sb, n) {
    .Call('_AoC2017_day15p2', PACKAGE = 'AoC2017', sa, sb, n)
}

